
public class Exception03 {
	public static void main(String[] args) {
		try {
			Exception03.division(100, 0);
		} catch (ArithmeticException e) {
			System.out.println("ArithmeticException例外が発生");
		} catch (IllegalArgumentException e) {
			System.out.println("IllegalException例外が発生");
			throw e;
		}
		System.out.println("プログラム終了");
	}

}
